openapi: '3.0.2'
info:
  title: User Service
  version: '1.0'
paths:
  /auth/verify:
    get:
      summary: Verify JWT
      description: Verify if JWT is valid
      tags:
        - "Authentication"
      responses:
        '200':
          description: Successfull verify
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
        '400':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/revoke:
    get:
      summary: Revoke JWT
      description: Revoke the validity of the JWT
      tags:
        - "Authentication"
      responses:
        '200':
          description: Successfull verify
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
        '500':
          $ref: '#/components/responses/InternalError'

components:
  responses:
    Unauthorized:
      description: Invalid JWT token or JWT token not found
      content:
        application/json:
          schema:
            $ref: './types/ErrorResponse.openapi.yml'
          example:
            message: Invalid JWT token provided

    InternalError:
        description: Invalid token or token not found
        content:
          application/json:
            schema:
              $ref: './types/ErrorResponse.openapi.yml'
            example:
              message: Internal server error occurred

  securitySchemes:
    jwt:
      type: apiKey
      in: cookie
      name: access_token
    sessionToken:
      type: apiKey
      in: header
      name: crsf_token

security:
  - jwt: []
  - sessionToken: []