type: object
properties:
  id:
    $ref: './PlugId.openapi.yml'
  name:
    type: string
    example: "Send email when received discord DM"
  activated:
    type: boolean
  event:
    $ref: '../events/Event.openapi.yml'
  actions:
    $ref: '../actions/ActionsList.openapi.yml'
