type: object
properties:
  id:
    $ref: './ServiceId.openapi.yml'
  name:
    type: string
    example: GMail
  connected:
    type: boolean
  icon:
    type: string
    example: '/images/reddit_icon.png'
    description: URI to the icon image
  triggers:
    $ref: '../triggers/TriggersList.openapi.yml'
  actions:
    $ref: '../actions/ActionsList.openapi.yml'